name: Pipeline tercera convocatoria josbragar
on:
  push:
    branches:
      - 'testa'
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' #Versión con la que haya creado el proyecto
      - name: Ejecutar los test
        run: |
          chmod +x gradlew 
          ./gradlew test